### ISSUE TITLE
Will there be a windows version ?

### ISSUE THREAD

**Issue by bebunw** [kandayo/likee-scraper#1]
Title.

**Comment by carsoh** [comment]
You can use Ubuntu in Windows 10 ( https://www.microsoft.com/store/productId/9NBLGGH4MSV6 ) to use this.
Note: its a bit tricky to install as there is a lot of dependencies missing in Ubuntu for Windows.

**Comment by alanblue2000** [comment]
Using Windows subsystem Ubuntu, looks like successful API request for username, HOWEVER, using either @username or ID no videos are downloaded, see prompts:

**~/likee-scraper$ ./bin/likeer -u 01234567**

**Downloading 1 profiles: 01234567**

**Collecting videos from profile 01234567**

Any ideas? Any help appreciated.

**Comment by lucasintel** [comment]
@alanblue2000 can you create a new issue?

I noticed that Likee is blocking some IP addresses. I'll look into it.

For now, this issue can be mitigated using proxies (or a VPN).

**Comment by lucasintel** [comment]
https://github.com/kandayo/likee-scraper/issues/5
