### ISSUE TITLE
incompatible with crystal 1.1.0

### ISSUE THREAD

**Issue by sikoGD** [kandayo/likee-scraper#2]
is there any forecast for updates?

**Comment by lucasintel** [comment]
For now, build it with the `--ignore-crystal-version`.

```sh
$ git clone https://github.com/kandayo/likee-scraper
$ cd likee-scraper
$ shards build --release --ignore-crystal-version
$ ./bin/likeer --help
```
 
I updated the README and updated the CI to test against both `0.36.1` and `latest`.

Also I attached a static linked pre-built binary here: https://github.com/kandayo/likee-scraper/releases/tag/v0.2.3. Just rename it to `likeer` and move it to your PATH (usually `~/.local/bin` or `/usr/bin`).

**Comment by sikoGD** [comment]
it worked, thanks you are amazing

**Comment by bek2d** [comment]
@kandayo  Pre-built binary, latest version 0.2.4 

An error occoured while executing request; retring (1/5)
...
An error occoured while executing request; retring (5/5)

Unhandled exception: Likee API code 50003: system error (Likee::APIError)
  from /app/lib/likee/src/likee/client.cr:25:7 in 'download_user'
  from /app/src/likee_scraper.cr:35:7 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
