### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by stonedmonkey** [kandayo/likee-scraper#3]
I have been using the same batch file and command every day to backup a few accounts, today it is saying susers not found whilst i double checked the apps and the accounts are still active.

**Comment by stonedmonkey** [comment]
Upon further examination download by username function is not working but if we input in the user ID then it works as normal. This may possibly be due to API changes. OP if you have time can you please investigate?

**Comment by lucasintel** [comment]
Thank you for the report. 

Fixed in v0.2.4: https://github.com/kandayo/likee-scraper/releases/tag/v0.2.4.
Just grab the binary from the Github release or compile it yourself.

Diff: https://github.com/kandayo/likee-scraper/compare/v0.2.3...v0.2.4.

Let me know if you have any issues.

**Comment by lucasintel** [comment]
By the way, the integration tests were not actually running 🤦🏻. That's why the build was passing.
