### ISSUE TITLE
Unable to download videos

### ISSUE THREAD

**Issue by carsoh** [kandayo/likee-scraper#5]
Hi, seems like Likee has changed somethings so downloads no longer work like they used to.

It just starts and find no videos.  Opening a Likee profile on the web also shows no videos.

Did some testing with VPN (NordVPN) and found that when changing it to the same country as the Likee profil I can then download, and view video in the browser. But only for that one/set of profiles from that country.

**Comment by lucasintel** [comment]
I second it. They changed the web API.

I'm looking into it. For now, this issue can be mitigated using a Singapore proxy/VPN.

**Comment by lucasintel** [comment]
Still looking for a way to bypass the geo blocking.

I will try to make it easy to rotate proxies based on the profile country code.

**Comment by santosadrian** [comment]
Then is only geoblocking? I have AirVPN, I'm gonna try changing country.

Singapore VPN is valid for all countries? Or just singapore?

If you wanna beta testers I have VPN, Win10, Debian, Ubuntu and Kali.

**Comment by lucasintel** [comment]
Oh I forgot to post an update here. They reverted the web API changes after two or three weeks.
